alias: notify_when_airbnb_frontdoor_opened
trigger:
  - platform: state
    entity_id: binary_sensor.aqara_airbnb_door # Airbnb door sensor
    to: 'on'
action:
  - service: notify.all_devices
    data:
      message: 'Airbnb door was opened at {{now().strftime("%-I:%M %p")}}'
      data:
        push:
          thread-id: "airbnb-door"
