alias: notify_when_airbnb_frontdoor_closed
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_7787247e # Airbnb door sensor
    to: 'off'
action:
  - service: notify.all_devices
    data:
      message: 'Airbnb door was closed at {{now().strftime("%-I:%M %p")}}'
      data:
        push:
          thread-id: "airbnb-door"
