alias: notify_if_frontdoor_open
trigger:
  - platform: time_pattern
    minutes: '/20'
    seconds: 0
condition:
  - condition: state
    entity_id: binary_sensor.wyzesense_778727e0 # Front door sensor
    state: 'on'
action:
  - service: notify.all_devices
    data:
      message: 'Remember the front door is open'
      data:
        push:
          thread-id: "front-door"
