alias: notify_when_frontdoor_closed
trigger:
  - platform: state
    entity_id: binary_sensor.aqara_front_door # Front door sensor
    to: 'off'
action:
  - service: notify.all_devices
    data:
      message: 'Front door was closed at {{now().strftime("%-I:%M %p")}}'
      data:
        push:
          thread-id: "front-door"
