alias: bathroom_lights_off
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779B08BC # Bathroom motion sensor
    to: 'off'
    for:
      minutes: 5
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeon_labs_zw116_nano_switch_switch_3 # Bathroom lights