alias: bathroom_lights_on
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779B08BC # Bathroom motion sensor
    to: 'on'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.aeon_labs_zw116_nano_switch_switch_3 # Bathroom lights