alias: bedroom_motion_lights_on
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779b1600 # Bedroom motion sense
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.in_bed
      state: 'off'
    - condition: state
      entity_id: binary_sensor.after_hours_light
      state: 'on'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.aeon_labs_zw132_dual_nano_switch_switch_4 # Bedroom light
     