alias: entrance_motion_lights_off
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779B044A # Entrance motion sensor
    to: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeon_labs_zw132_dual_nano_switch_switch_15 # Entrance & door lights