alias: garage_lights_on
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779B265D # Garage motion sensor
    to: 'on'
# condition:
#   - condition: state
#     entity_id: binary_sensor.wyzesense_77937934 # Garage door sensor
#     state: 'off'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.aeon_labs_zw116_nano_switch_switch_2 # Garage lights