alias: garage_lights_on
trigger:
  - platform: state
    entity_id: binary_sensor.aqara_garage_motion_sensor # Garage motion sensor
    to: 'on'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.aeon_labs_zw116_nano_switch_switch_2 # Garage lights