alias: kitchen_lights_off
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: 'Kitchen lights off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeon_labs_zw132_dual_nano_switch_switch_2 # Kitchen