alias: lights_on_arrival
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_77937934 # Garage door sensor
    to: 'on'
  - platform: state
    entity_id: binary_sensor.wyzesense_778727e0 # Front door sensor
    to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.after_hours_light
    state: 'on'
action:
  - service: script.turn_on
    data:
      entity_id: script.entrance_lights_on