alias: lights_on_arrival
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_77937934 # Garage door sensor
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -6
action:
  - service: script.turn_on
    data:
      entity_id: script.entrance_lights_on