alias: pantry_lights_off
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779B0501 # Kitchen motion sensor
    to: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeon_labs_zw132_dual_nano_switch_switch_3 # Pantry