alias: pantry_lights_on
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_77938e48 # Pantry door sensor
    to: 'on'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.aeon_labs_zw132_dual_nano_switch_switch_3 # Pantry