alias: stairs_motion_lights_off
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779b23bf # Stairs motion sensor
    to: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeon_labs_zw132_dual_nano_switch_switch_12 # Stairs lights
