alias: stairs_motion_lights_on
trigger:
  - platform: state
    entity_id: binary_sensor.aqara_stairs_motion_sensor # Stairs motion sensor
    to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.after_hours_light
    state: 'on'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.aeon_labs_zw132_dual_nano_switch_switch_12 # Stairs lights