alias: wardrobe_motion_lights_off
trigger:
  - platform: state
    entity_id: binary_sensor.aqara_wardrobe_motion_sensor # Wardrobe motion sense
    to: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeon_labs_zw116_nano_switch_switch # Wardrobe light
