alias: wardrobe_motion_lights_off
trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_7787b931 # Wardrobe motion sense
    to: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeon_labs_zw116_nano_switch_switch # Wardrobe light
