alias: notify_on_home_departure
trigger:
  - platform: state
    entity_id: person.hady_osman
    to: 'not_home'
action:
  - service: notify.mobile_app_hady_s_iphonex
    data:
      message: 'Did you just leave the house?'