alias: notify_on_home_arrival
trigger:
  - platform: state
    entity_id: person.hady_osman
    to: 'home'
action:
  - service: notify.mobile_app_hady_s_iphone_xii
    data:
      message: 'Looks like you just arrived? Welcome home!'