alias: turn_on_wfh_boolean_weekdays
trigger:
  - platform: time
    at: "08:00:00"
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.wfh
  - service: notify.mobile_app_hady_s_iphone_xii
    data:
      message: 'Morning! WFH mode has been turned on. Have a wonderful day!'
